language: perl6
sudo: false
os:
  - linux
  - osx
perl6:
  - latest
  - '2018.10'
  - '2019.03'
install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install File::Temp
  - zef build .
script:
  - prove -ve "perl6 -I."
  - zef install .
